### ISSUE TITLE
pretrained wider_resnet38.pth.tar file

### ISSUE THREAD

**Issue by lzyuan168** [vt-le/astnet#12]
Hi,

Thank you for providing the repo. May I know where can I download the wider_resnet38.pth.tar file that is supposed to be in ../../datasets/seg_weights folder mentioned in the ped2_wresnet.yaml file.

Thank you

**Comment by vt-le** [comment]
> Hi,
> 
> Thank you for providing the repo. May I know where can I download the wider_resnet38.pth.tar file that is supposed to be in ../../datasets/seg_weights folder mentioned in the ped2_wresnet.yaml file.
> 
> Thank you

Thanks for your interest.

Pretrained Wider Resnet can be downloaded here: [https://github.com/mapillary/inplace_abn/](https://github.com/mapillary/inplace_abn/)
