### ISSUE TITLE
training from scratch

### ISSUE THREAD

**Issue by MarkInada** [vt-le/astnet#3]
Hi, is it possible to train the model? I could not find any code to train model. 

I am wondering how to create the pre-trained model (UCSD Ped2, CUHK Avenue, ShanghaiTech Campus). Is this repository inference only?

Thank you.

**Comment by djy9809** [comment]
> Hi, is it possible to train the model? I could not find any code to train model.
> 
> I am wondering how to create the pre-trained model (UCSD Ped2, CUHK Avenue, ShanghaiTech Campus). Is this repository inference only?
> 
> Thank you.

I have the same question with you, have you already resovled it?

**Comment by lv-tuan** [comment]
> Hi, is it possible to train the model? I could not find any code to train model.
> 
> I am wondering how to create the pre-trained model (UCSD Ped2, CUHK Avenue, ShanghaiTech Campus). Is this repository inference only?
> 
> Thank you.

Hi, thank you for your interest!
I don't have permission to release the training code of this project. However, I can contribute to your repository.

**Comment by vt-le** [comment]
Hi, thank you for your interest!
I don't have permission to release the training code. However, I can contribute to your repository if you need help.
