### ISSUE TITLE
Detect anomaly on test video

### ISSUE THREAD

**Issue by Forchapeatl** [vt-le/astnet#4]
Thanks for the code , how can one detect anomaly on test video

**Comment by vt-le** [comment]
Hi, thank you for your interest!
You can follow the guide [(here)](https://github.com/vt-le/astnet/blob/main/README.md). There are several steps:
- Clone the project
- Download an anomaly dataset and pretrained model
- Prepare your dataset

**Comment by Forchapeatl** [comment]
@vt-le , thank you. Please how my i visuaize the results on sample video 
![image](https://user-images.githubusercontent.com/24577149/179486921-b09efa34-e77a-43d2-bab1-f4beb63b0ec3.png)

**Comment by vt-le** [comment]
> @vt-le , thank you. Please how my i visuaize the results on sample video ![image](https://user-images.githubusercontent.com/24577149/179486921-b09efa34-e77a-43d2-bab1-f4beb63b0ec3.png)
> 
> I have gone through the config file. Please how may i pass file "video.mp4" as parameter ?

Hi,
- In this repository, we don't provide the code for visualization. 

- You cannot pass a name a video as the input. Only a name of a anomaly detection dataset [Ped2 / Avenue / ShanghaiTech] is accepted in [config file](https://github.com/vt-le/astnet/blob/main/experiments/ped2/ped2_wresnet.yaml).

**Comment by Forchapeatl** [comment]
Thank you

**Comment by hhhh1230kvj** [comment]
Thank you for your work, I just started this field, could you please send me your visualization code, thank you very much.1418319084@qq.com

**Comment by hhhh1230kvj** [comment]
Thank you for your work, I just started this field, could you please send me your visualization code, thank you very much. 1418319084@qq.com.

**Comment by lq-zhu** [comment]
@vt-le  Thanks for the code. I have finished all the preparations, but it's failed when test the dataset by running the following command.  The "file" in "--cfg /path/to/config/file" confused me. If I want to test the avenue dataset, can you provide me with the correct run command?

![image](https://user-images.githubusercontent.com/126659050/222088338-9c9ea931-a174-4908-801c-a6f2d758e34e.png)


> Hi, thank you for your interest! You can follow the guide [(here)](https://github.com/vt-le/astnet/blob/main/README.md). There are several steps:
> 
> * Clone the project
> * Download an anomaly dataset and pretrained model
> * Prepare your dataset

**Comment by vt-le** [comment]
> @vt-le Thanks for the code. I have finished all the preparations, but it's failed when test the dataset by running the following command. The "file" in "--cfg /path/to/config/file" confused me. If I want to test the avenue dataset, can you provide me with the correct run command?
> 
> ![image](https://user-images.githubusercontent.com/126659050/222088338-9c9ea931-a174-4908-801c-a6f2d758e34e.png)
> 
> > Hi, thank you for your interest! You can follow the guide [(here)](https://github.com/vt-le/astnet/blob/main/README.md). There are several steps:
> > 
> > * Clone the project
> > * Download an anomaly dataset and pretrained model
> > * Prepare your dataset

Hi @lq-zhu ,
You can download the pre-trained model and save to **pre_trained** folder, then you can run like so:
`python astnet.py --cfg experiments/ave/ave_wresnet.yaml --model-file pre_trained/avenue.pth GPUS [1]`

**Comment by lq-zhu** [comment]
Thank you
