### ISSUE TITLE
Residual channel attention block

### ISSUE THREAD

**Issue by fanzz1208** [vt-le/astnet#6]
What part of the code is Residual channel attention block？ 

Please tell me， thank you

**Comment by vt-le** [comment]
Hi, thank you for your interest!

Channel Attention is defined here: [https://github.com/vt-le/astnet/blob/141f9d57c8dd121bef072797533c413546e54c18/networks/helper.py#L69](https://github.com/vt-le/astnet/blob/141f9d57c8dd121bef072797533c413546e54c18/networks/helper.py#L69)

**Comment by fanzz1208** [comment]
for Residual channel attention block ,  how to define? just add conv and relu and conv ?

**Comment by vt-le** [comment]
> for Residual channel attention block , how to define? just add conv and relu and conv ?

Residual channel attention block is defined here: [https://github.com/vt-le/astnet/blob/f8c53790cfae84416086284587fe0f33300708ab/networks/helper.py#L122](https://github.com/vt-le/astnet/blob/f8c53790cfae84416086284587fe0f33300708ab/networks/helper.py#L122)
