### ISSUE TITLE
avenue datasets

### ISSUE THREAD

**Issue by 16422004** [vt-le/astnet#7]
Hi, thanks for your work, i am wondering could you share the avenue test dataset which you used for this project please, email(17681262923@163.com) or google driver. Thank you.

**Comment by vt-le** [comment]
> Hi, thanks for your work, i am wondering could you share the avenue test dataset which you used for this project please, email([17681262923@163.com](mailto:17681262923@163.com)) or google driver. Thank you.

Hi, thanks for your interest!

You can download the Avenue dataset here: [http://www.cse.cuhk.edu.hk/leojia/projects/detectabnormal/dataset.html](http://www.cse.cuhk.edu.hk/leojia/projects/detectabnormal/dataset.html)
