### ISSUE TITLE
train model

### ISSUE THREAD

**Issue by wmlwrl** [vt-le/astnet#8]
Hello, I want to write the train model myself, but the AUC of the training model I wrote is only 79% on the ped2 dataset, you may help me

**Comment by vt-le** [comment]
> Hello, I want to write the train model myself, but the AUC of the training model I wrote is only 79% on the ped2 dataset, you may help me

Hi, 
Could I contribute to your repository?

VT-Le

**Comment by wmlwrl** [comment]
I would really appreciate it if you could send me the training code.

**Comment by vt-le** [comment]
> I would really appreciate it if you could send me the training code.

I'm sorry. I don't have permission to share the training script now. We will share it after our project finishes.

**Comment by wmlwrl** [comment]
Hello, I have updated my repository, can you help me take a look

**Comment by wmlwrl** [comment]
https://github.com/wmlwrl/astnet_test.git

**Comment by wmlwrl** [comment]
This is my repository above link,I would appreciate it if you could help me

**Comment by vt-le** [comment]
> This is my repository above link,I would appreciate it if you could help me

I have sent an email to you.

**Comment by wmlwrl** [comment]
thank you very much
